name: Deploy Prod

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to gh-pages (root)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./            # statik kök; build’in yoksa bu
          keep_files: true
          exclude_assets: |
            .github, .gitignore, README.md, LICENSE
          commit_message: "prod: ${{ github.sha }}"
